language: python
sudo: false

env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"
  - PIP_DEPS="pytest==3.6 coveralls pytest-cov flake8"  

python:
- '3.6'

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib pytest pytest-cov pandas"
  - activate test-environment
  - pip install coverage
  - python setup.py install

test_script:
  - mkdir for_test
  - cd for_test
  - py.test --pyargs kmpy --cov-report term-missing --cov=kmpy
